name: example
description: An example project for the animated_navigation_bar package

version: 1.0.0

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  animated_navigation_bar:
      path: ../

flutter:
  uses-material-design: true